services:
    web:
        image: baiasen72/m5-homework-web 
        ports:
            - 80:8080
        volumes:
            - "/home/jenkins/workspace/M5_Homework/web:/var/www/html:ro"
        networks:
            - homework
    db:
        image: baiasen72/m5-homework-db
        networks:
            - homework
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    homework:
